In [3]:
import pandas as pd

a = pd.DataFrame({'Yes':[ 12 , 31 ] , 'No' : [55 , 13]})

a

   Yes  No
0   12  55
1   31  13

In [4]:
# we can also use the strings in it 

b = pd.DataFrame({ 'Bob':['Hey i am bob','I am a trader'] , 'Alice':['Hey i am alice', ' I am a analyst'] } )

b

             Bob            Alice
0   Hey i am bob   Hey i am alice
1  I am a trader   I am a analyst

In [10]:
# we can also set the index as per our need

c = pd.DataFrame({ 'Bob':[ 'I am bob' , ' i am a trader '] , 
                   'Alice' : [ 'I am alice' , ' i am a analyst'] }, 
                   index = [ ' Introduction ' ,'Profession'] )

c

                            Bob            Alice
 Introduction          I am bob       I am alice
Profession       i am a trader    i am a analyst

In [11]:
# now we will learn about series 
# series can be created by the use of list and it dosent have column name but it has the overall name

d = pd.Series( [ 30 , 40 , 50 ] )
d

0    30
1    40
2    50
dtype: int64

In [12]:
# we can also change the name of the index and we can also give the overall name to the series 

e = pd.Series( [ 30 , 45 , 60 ] , index = [ ' 2024 sale ' , ' 2025 sale ' , ' 2026 sale ' ] , name = 'product' )

e

2024 sale     30
2025 sale     45
2026 sale     60
Name: product, dtype: int64

In [15]:
# now we will learn to read the csv file 

f = pd.read_csv('task1.csv')
f

   Product A  Product B  Product C  Unnamed: 3
0         30         21          9         NaN
1         35         34          1         NaN
2         41         11         11         NaN

In [16]:
# to check the size/shape of the dataframe
f.shape # it will answer as ( row , column )

(3, 4)

In [23]:
# now we will learn to read the long data 
e = pd.read_csv( r"C:\Users\HP\Documents\GitHub\Quant-Journey\month-01- python for finance\Week 2.0 - Pandas\winemag-data-130k-v2\winemag-data-130k-v2.csv")

e.head() # head() will print the top 5 datas

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [24]:
# to remove this unnamed column we can use the function of index_col = 0
f = pd.read_csv( r"C:\Users\HP\Documents\GitHub\Quant-Journey\month-01- python for finance\Week 2.0 - Pandas\winemag-data-130k-v2\winemag-data-130k-v2.csv" , index_col = 0 )
f.head(3)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm